/*
 * 	Copyright (C) 2005-2011 Department of Enteprise Engineering, University of Rome "Tor Vergata"
 *                              ( http://www.dii.uniroma2.it )
 *
 *      This file is part of jEQN and was developed at the Software Engineering Laboratory
 *      ( http://www.sel.uniroma2.it )
 *
 *      jEQN is free software: you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation, either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      jEQN is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with jEQN.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package it.uniroma2.sel.simlab.jeqn.users;

import java.util.ArrayList;

/** Represents a clone user of an "original" user passing through a Split node.
 *
 * @author Daniele Gianni
 */
public class CloneUser extends User {

    // the original user the clone has been generated from
    private User cloned;

    // number of the copy in the set of clone users generated by the Split node
    private Integer copyNumber;
    
    /** 
     * Creates a new instance of CloneUser
     * @param toClone The user to be cloned
     */
    public CloneUser(final User toClone) {
        super(toClone);
        
        setCloned(toClone);
        setCopyNumber(0);
    }
    
    /**
     * Creates a new instance of CloneUser
     * @param toClone the user to be cloned 
     * @param copyNumber the number of clones that have to be generated
     */
    public CloneUser(final User toClone, final Integer copyNumber) {
        super(toClone);
        
        setCloned(toClone);
        setCopyNumber(copyNumber);
    }

    /**
     * Static method that returns an instance of CloneUser by wrapping the specified user.
     * @param u user to be cloned
     * @return The CloneUser that wraps the specified user
     */
     
    public static CloneUser wrap(final User u) {
        return new CloneUser(u);
    }

    /**
     * Static method that returns an instance of CloneUser with the specified number of clones. It wraps the specified user.
     * @param u User to be cloned.
     * @param i the number of clones that have to be generated
     * @return The new instance of CloneUser.
     */
    
    public static CloneUser wrap(final User u, final Integer i) {
        return new CloneUser(u, i);
    }        

    /**
     * Static method that returns a list of cloned user, generated from an original user.
     *      
     * @param toClone user to be cloned 
     * @param numberOfClones the number of clones that have to be generated
     * @return the list of clones
     */
     
    public static ArrayList<CloneUser> clone(final User toClone, final Integer numberOfClones) {
    
        ArrayList<CloneUser> clones = new ArrayList<CloneUser>(numberOfClones);
        
        for (int i = 0; i < numberOfClones; i++) {
            clones.add(new CloneUser(toClone, i));
        }
        
        return clones;        
    }
    
    /**
     * Gets the orignal user wrapped into the CloneUser
     * @return the wrapped user to be cloned
     */
    public User getClone() {
        return cloned;
    }
    
    /**
     * Gets the number of clones that have to be generated
     * @return Number of clones
     */
    public Integer getCopyNumber() {
        return copyNumber;
    }
    
    public String getName() {
        return "Clone" + getCopyNumber() + "-" + cloned.getName();
    }
    
    protected void setCloned(final User u) {
        cloned = u;
    }
    
    public void setCopyNumber(final Integer i) {
        copyNumber = i;
    }
}
