/*
 * 	Copyright (C) 2005-2011 Department of Enteprise Engineering, University of Rome "Tor Vergata"
 *                              ( http://www.dii.uniroma2.it )
 *
 *      This file is part of jEQN and was developed at the Software Engineering Laboratory
 *      ( http://www.sel.uniroma2.it )
 *
 *      jEQN is free software: you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published by
 *      the Free Software Foundation, either version 3 of the License, or
 *      (at your option) any later version.
 *
 *      jEQN is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 *
 *      You should have received a copy of the GNU General Public License
 *      along with jEQN.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package it.uniroma2.sel.simlab.jeqn.waiting.times;

/**
 *
 * @author  Daniele Gianni
 */
public class SwitchingTimesFileCreator extends javax.swing.JFrame {
    
    /** Creates new form SwitchingTimesFileCreator */
    public SwitchingTimesFileCreator() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        RowsTextField = new javax.swing.JTextField();
        jTable1 = new javax.swing.JTable();
        Rows = new javax.swing.JLabel();
        Column = new javax.swing.JLabel();
        ColumnsTextField = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        FileNameLabel = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        setTitle("Constant Switching Time Creator");
        setBackground(new java.awt.Color(153, 153, 255));
        setFont(new java.awt.Font("Arial", 0, 10));
        setForeground(new java.awt.Color(153, 153, 255));
        setName("Constant Switching Time Creator");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        RowsTextField.setText("2");
        RowsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RowsTextFieldActionPerformed(evt);
            }
        });

        getContentPane().add(RowsTextField);
        RowsTextField.setBounds(80, 20, 60, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        getContentPane().add(jTable1);
        jTable1.setBounds(200, 0, 200, 300);

        Rows.setText("Rows");
        getContentPane().add(Rows);
        Rows.setBounds(10, 20, 50, 30);

        Column.setText("Columns");
        getContentPane().add(Column);
        Column.setBounds(10, 80, 50, 16);

        ColumnsTextField.setText("5");
        getContentPane().add(ColumnsTextField);
        ColumnsTextField.setBounds(80, 70, 60, 30);

        CreateButton.setText("Create");
        getContentPane().add(CreateButton);
        CreateButton.setBounds(50, 220, 72, 26);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 120, 63, 20);

        FileNameLabel.setText("FileName");
        getContentPane().add(FileNameLabel);
        FileNameLabel.setBounds(10, 120, 60, 16);

        pack();
    }//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void RowsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RowsTextFieldActionPerformed
        // Add your handling code here:       
    }//GEN-LAST:event_RowsTextFieldActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new SwitchingTimesFileCreator().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Column;
    private javax.swing.JTextField ColumnsTextField;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel FileNameLabel;
    private javax.swing.JLabel Rows;
    private javax.swing.JTextField RowsTextField;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
